### ISSUE TITLE
Not capturing STDOUT/STDERR

### ISSUE THREAD

**Issue by aconite33** [nettitude/RunPE#10]
When running certain PE files, the STDOUT/STDERR is not be captured approximately. 

```
RunPE Version: Latest
OS: Windows 10
Build: OS Version: 10.0.19045 N/A Build 19045
```

Example running Mimikatz (latest):

![image](https://user-images.githubusercontent.com/3675886/208531876-ce3aec09-2608-4e61-88e2-c98b81c24153.png)

[...snippet...]

![image](https://user-images.githubusercontent.com/3675886/208531967-7570da73-22f6-4094-9e6b-f8ed5a2d2fc4.png)

As you can see, the execution of the PE works, however no output is pushed to the redirection pipe handlers.

I am using our C2 to wrap this functionality and when I try to get the output, there is nothing that is returned (https://github.com/nettitude/RunPE/blob/main/RunPE/Program.cs#L107)

I have also tried the CheekyBlinders (https://github.com/br-sn/CheekyBlinder) PE file, which results in the same issue of no output being collected.

**Comment by m0rv4i** [comment]
Hi @aconite33 , thanks for the issue, however I'm not able to reproduce locally. Are you able to let us know:

- What C2 you are using? 
- What version of mimikatz.exe are you using (git hash)
- If you run it directly from the CLI does it work?

E.g. 

`runpe.exe C:\users\user\Downloads\mimikatz.exe coffee exit` gives me

![image](https://user-images.githubusercontent.com/20513519/211342459-260fd4a1-105d-413d-8c87-b3a9293870b4.png)

**Comment by aconite33** [comment]
C2: Private C2 we develop
Latest version of [Mimikatz](https://github.com/gentilkiwi/mimikatz/commit/746e2116d1fb754f41fc13abd182a5a0efb6dad9)
CLI has the same output/response when we wrap it into the C2.

@benpturner was able to get it working on his side, so I don't know if this is an 'us' issue, e.g., are we compiling it incorrectly?

**Comment by m0rv4i** [comment]
I'm also unable to reproduce your issue locally (see my screenshot above) but I'll look into it a bit more, thanks for the quick response!

**Comment by m0rv4i** [comment]
Just rebuilt latest mimikatz and runpe and still unable to reproduce, may need more details to get any further. I have push a couple of minor changes as well as updating the target framework so maybe double check none of that changed anything?

![image](https://user-images.githubusercontent.com/20513519/211361077-bdf425b0-54cf-4b72-b228-d5c022180744.png)

**Comment by aconite33** [comment]
@m0rv4i 

Just pulled the latest, built on Visual Studio 2022. Target Framework 4.5.1. Same Result


![image](https://user-images.githubusercontent.com/3675886/211362953-3a8f8590-52bf-4277-9566-e3663706fd59.png)


![image](https://user-images.githubusercontent.com/3675886/211362990-961da11e-3fe8-46dc-bba3-731fca3fddcd.png)


![image](https://user-images.githubusercontent.com/3675886/211363032-8422741a-fefe-48cd-90f3-bc56b8cd8b4a.png)

**Comment by aconite33** [comment]
Also tried targeting .Net Framework 4.8


![image](https://user-images.githubusercontent.com/3675886/211363356-92ea76b4-cc37-4f02-87d3-abcf2f6a0410.png)

**Comment by aconite33** [comment]
@m0rv4i same with Windows 11 (Enterprise, latest updates) Mimikatz (latest release), Visual Studio 2022.

![image](https://user-images.githubusercontent.com/3675886/211389228-c4fbb784-d7c7-47a2-9afd-1cac05bec2dd.png)

![image](https://user-images.githubusercontent.com/3675886/211389309-bd9bd66c-953f-4b2b-831a-a395cabb8376.png)

![image](https://user-images.githubusercontent.com/3675886/211389358-285335e2-eba7-4d0f-a87e-23dd96f1f433.png)

**Comment by aconite33** [comment]
Checking in again.

I tried pulling a fresh install Windows 10 Enterprise, latest updates.

Latest Mimikatz. I am still getting STDOUT/ERR issues. Screenshots below.

I am running QEMU Windows 10 Enterprise.

I also tried on a Windows 10 baremetal system and I still am getting the same results.

Is it possible to get a build from your guys end @m0rv4i so I can try to debug if it's on our side for compiling?

![image](https://user-images.githubusercontent.com/3675886/214116788-fe317e07-46d8-4f9e-a377-e6a420a47274.png)

![image](https://user-images.githubusercontent.com/3675886/214117011-d0df721d-a375-4d0c-b3f2-733b6a4f5cd3.png)

**Comment by aconite33** [comment]
@m0rv4i Well, after a bunch of debugging I built Mimikatz on my own systems and now I get the expected result and execution. The release version of MImikatz (running the exe from GitHub) gets you the same result I have been having. I am unsure what the difference is, but that solves the Mimikatz question.

The still outstanding issue is CheekyBlinders. I am still getting the same result as the release exe of Mimikatz.  I'm wondering if there is some underlying config on those .exe's that is causing RunPE not to pick up the output.

I noticed that the standard pipe redirection might be the culprit to why these release versions of Mimikatz and locally compiled CheekyBlinders seem to not pick up on the output redirection.

**Comment by aconite33** [comment]
> This is super useful, thanks @aconite33 - I'm on site atm so not much bandwidth but will investigate when I get time (probably next week)

Sounds good. We are still investigating on our side, if we come up with anything I'll continue this horribly long thread that I started! :smile:

**Comment by aconite33** [comment]
Anndddd boom goes the dynamite.

![image](https://user-images.githubusercontent.com/3675886/214317871-e9ebf5f7-14f8-489f-9799-a2247cd4cab5.png)


Any program you want to run within RunPE needs this changed when compiling with Visual Studio:

Project -> Properties -> C/C++ -> Code Generation -> RunTime Library -> Multi-Threaded Debug

Thanks to @kerrymilan for debugging it.

Here is CheekyBlinders running:

![image](https://user-images.githubusercontent.com/3675886/214318253-9b76e941-ae5f-4dcb-beb1-22f9b8fbed14.png)

**Comment by benpturner** [comment]
Nice find, we've definitely seen some of this in the past, e.g. static vs dynamic linking when running in memory. Must have had this configuration our side, i'll check and confirm as well 🙌

**Comment by m0rv4i** [comment]
Legends

**Comment by m0rv4i** [comment]
Thanks again all!

**Comment by bopin2020** [comment]
Test failed, even if change compilation to Multi-Threaded Debug.

**Comment by piolug93** [comment]
Same problem is with code
```
#include <windows.h>
#include <stdio.h>
#include <stdint.h>
#include <iostream>


int main() {
    std::cout << "Test" << std::endl;
    return 0;
}
```

Compiling with /MT no resolving problem. When i change std::cout to printf all is good.
